services:
  mysql:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./data:/docker-entrypoint-initdb.d
